### ISSUE TITLE
Additional Info

### ISSUE THREAD

**Issue by myeongjong-kim** [sharebook-kr/pykrx#26] opened 2020-09-22 00:42 UTC
Thank you for your help. 
My code still doesn't work.

1 def saveMarketCapDaily(targetDayStr):
2  targetDayStr="20200917"
3    print(stock.get_market_ticker_list("20200921"))
4    dfTargetDay = stock.get_market_cap_by_ticker(targetDayStr)
5    if (dfTargetDay.empty):
6        print('targetDay empty. day: ' + targetDayStr)
7        return -1
    ..

* line 3 shows empty list.
* dfTargetDay is empty. (with any date)

Environment
* Requirement already up-to-date: pykrx in c:\users\proje\appdata\local\programs\python\python38-32\lib\site-packages (0.1.41)
* Python 3.8.5 (32/64bit neither work)

**Comment by mr-yoo** [comment] 2020-09-22 15:53
Duplicate of #25

**Closed** 2020-11-18 08:03 UTC
Labels: duplicate
